<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\CustomerRegistration;
use Magento\Customer\Block\Account\Customer;
use Magento\Customer\Model\Account\Redirect;
use Magento\Framework\Escaper;

/** @var Customer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var CustomerRegistration $customerRegistration */
$customerRegistration = $viewModels->require(CustomerRegistration::class);
?>


  
        <?php if ($block->customerLoggedIn()): ?>
            <div x-data="{ open: false }" class="relative inline-block ml-1 sm:ml-3">

            <nav class="absolute right-0 z-20 hidden w-40 py-2 mt-2 -mr-4 px-1 overflow-auto origin-top-right rounded-sm
        shadow-lg sm:w-48 lg:mt-3 bg-container-lighter"
         :class="{ 'hidden' : !open }"
         @click.away="open = false"
         aria-labelledby="customer-menu"
    >
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>"
            >
                <?= $escaper->escapeHtml(__('My Account')); ?>
            </a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
            >
                <?= $escaper->escapeHtml(__('My Wish List')); ?>
            </a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('sales/order/history')) ?>"
            >
                <?= $escaper->escapeHtml(__('My Orders')); ?>
            </a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/address')) ?>"
            >
                <?= $escaper->escapeHtml(__('Address Book')); ?></a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/account/logout')) ?>"
            >
                <?= $escaper->escapeHtml(__('Sign Out')); ?>
            </a>
        </nav>
        </div>
        <?php else: ?>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100 relative after:h-[50%] after:w-[1px] after:absolute after:right-0 after:top-[11px] after:bg-gray-400 border-b border-solid border-[#9ca3af] before:absolute before:lg:top-9 before:h-1	before:w-[1px] before:left-0 before:bg-[#9ca3af] before:top-11"
               onclick="hyva.setCookie && hyva.setCookie(
                   '<?= /** @noEscape */ Redirect::LOGIN_REDIRECT_URL ?>',
                   window.location.href,
                   1
               )"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/account/index')) ?>">
               <div class="flex">
                <!-- userblack -->
               <?= $heroicons->userHtml('md:h-6 md:w-6  fill-[#00000085] stroke-[#7a7a7a]', 32, 32, ['aria-hidden' => 'true']); ?>
<span class="lg:block hidden uppercase text-[#343234] ">
<?= $escaper->escapeHtml(__('Sign In')); ?>
</span>
              
               </div>

            </a>

            <a class="flex px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100 relative after:h-[50%] after:w-[1px] after:absolute after:right-[-5px] after:top-[11px] after:bg-gray-400 border-b border-solid border-[#9ca3af] before:absolute before:lg:top-9 before:h-1	before:w-[1px] before:right-0 before:bg-[#9ca3af] before:top-11"
               href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
            >
            <?= $heroicons->  heartHtml('md:h-6 md:w-6 fill-[#00000085] stroke-[#7a7a7a]', 32, 32, ['aria-hidden' => 'true']); ?>
              
            <span class="lg:block hidden"><?= $escaper->escapeHtml(__('Favourites')); ?></span>
            </a>


            <?php if ($customerRegistration->isAllowed()): ?>
                <a class="hidden px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
                   href="<?= $escaper->escapeUrl($block->getUrl('customer/account/create')) ?>"
                >
                    <?= $escaper->escapeHtml(__('Create an Account')); ?>
                </a>
            <?php endif; ?>
        <?php endif; ?>

