<div  class="w-full">
   <div x-data="{ open: false ,event:43 , event2:47 }" class="w-full  max-w-[635px] inline-block addshadow px-[13px] pt-[13px] my-[10px] min-h-[90px] ">
      <button class="flex mt-[10px] leading-[2.5] text-xs font-ArnoProRegular text-black  hover:underline" x-on:click="open = ! open">
         CHOOSE A PEG HEAD 
         <svg xmlns="http://www.w3.org/2000/svg"
            fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-6 ml-[6px] text-[#565656]">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" stroke-width="2.5" />
         </svg>
      </button>
      <div x-show="open" >
         <div class="py-[10px]">
            <div class="flex">
               <div class="w-[25%] text-black font-ArnoProRegular text-[13px] mt-[5px]">HEAD TYPE</div>
               <div class="w-[58%]">
                  <select  x-data="setval($el.value) ;subchildval($el.value)" x-on:change.debounce="setval($el.value) ;subchildval($el.value);" id="catagories"
                     class=" text-[13px] rounded-none  block w-full pt-[3px] pb-0 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white   shadow-none border-l-0 border-r-0 border-t-0 border-b-[3px] border-solid border-[#bfbfbf] focus:border-[#bfbfbf] focus:shadow-none ">
                     <?php
                        $categoryId = 42;
                         
                        // Load category by category ID
                        $category = $block->getCategory($categoryId);
                        
                        
                        
                        // Get comma-separated children category ids
                        $childrenCategoryIds = $block->getChildren($categoryId);
                        $childrenArray = explode (",", $childrenCategoryIds); 
                        
                        foreach($childrenArray as $Id){
                        
                           ?> 
                     <option value="<?= $Id; ?>" ><?php echo $block->getCategoryNameById($Id, $storeId = null);
                        $categoryId=$block->getCategoryNameById($Id, $storeId = null);
                        ?>
                     </option>
                     <?php
                        }
                        
                        
                        ?>
                  </select>
               </div>
            </div>
            <div class="flex">
               <div class="w-[25%] text-black font-ArnoPro text-[13px] mt-[5px]">CENTER SHAPE</div>
               <div class="w-[58%]">
                  <select  x-on:change.debounce=" subchildval($el.value)"  id="subchilds"
                     class=" text-[13px] rounded-none  block w-full pt-[3px] pb-[5px] dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500  shadow-none border-l-0 border-r-0 border-t-0 border-b-[3px] border-solid border-[#bfbfbf] focus:border-[#bfbfbf] focus:shadow-none">
                  </select>
               </div>
            </div>
         </div>
         <div>
            <div id="slides-container" class="flex w-full max-w-[360px] overflow-hidden m-auto">
               <ul id="catagoryproducts" class="flex ease-in-out duration-300 px-[10px] w-full" >
               </ul>
            </div>
            <div class="btns">
               <button id="btn-prev" class="relative top-[-75px] left-[27px] ">
               <img class="w-[30px]" src="<?php echo $this->getViewFileUrl('images/leftarrownew.webp'); ?>" >
               </button>
               <button id="btn-next" class="relative top-[-105px] float-right right-[37px]">
               <img class="w-[30px]" src="<?php echo $this->getViewFileUrl('images/rightarrownew.webp'); ?>" >
               </button>
            </div>
            <div class="text-center top-[-20px] relative text-[15px]  capitalize m-0" id="matchingsectionpegheadlink"><a href="" class=" text-[#337ab7] hover:underline hover:text-[#3399cc]"  id="fancybox">select center size</a></div>
         </div>
      </div>
   </div>
</div>
</div>
<div id="myModal" class="modal hidden">
   <div
      class="fixed inset-0 z-30 flex items-center justify-center overflow-auto bg-black bg-opacity-50"
      >
      <!-- Modal inner -->
      <div
         class=" max-w-[950px] p-[10px] mx-auto text-left bg-white  shadow-lg relative w-full overflow-y-scroll h-[100%]  top-[16px] lg:overflow-y-none lg:overflow-hidden lg:h-auto lg:m-auto lg:top-0 m-[27px]"
         @click.away="showModal = false"
         x-transition:enter="motion-safe:ease-out duration-300"
         x-transition:enter-start="opacity-0 scale-90"
         x-transition:enter-end="opacity-100 scale-100"
         >
         <div class="border border-solid border-[#ccc]">
            <!-- Title / Close-->
            <div class="flex items-center justify-between">
               <h5 class="  max-w-none text-center text-white text-2xl p-[15px] bg-black border border-solid border-black font-Montserrat w-full">Peg Head for your Engagement Ring</h5>
               <button type="button" class="close z-50 cursor-pointer absolute top-[1px] right-[1px] shadow-lg border rounded-full border-solid border-black	" @click="showModal = false">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="white" class="p-[2px] bg-black rounded-full border-[2px] border-solid border-white   ">
                     <path stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M6 18L18 6M6 6l12 12" />
                  </svg>
               </button>
            </div>
            <!-- content -->
            <div class="w-auto  mx-auto   inline-block mt-[15px]">
               <div id="content" class="w-full mx-auto inline-block font-ArnoProRegular text-[13px] float-left relative min-h-[1px] px-[15px]">
                  <div class="block w-auto  mx-auto  ">
                     <div class="lg:w-1/2 md:w-full  mx-auto   inline-block float-left relative min-h-[1px] pl-0 pr-[15px]">
                        <div class="text-center font-ArnoProRegular text-black text-[13px]" >
                           <img  id="img01" width="300" height="300">
                        </div>
                        <input name="customerprice_carousel" id="customerprice_carousel" type="hidden" value="$127.17">
                        <div class="w-full m-0  inline-block">
                           <div class="md:w-full  mx-auto   inline-block float-left  w-full relative min-h-[1px]  mt-[-5px]">
                              <div class="infobottom prod_des">
                                 <h4 class=" relative min-h-[1px] px-[15px] pl-[20px] bg-[#E4EDF4] text-[13px] font-bold w-full leading-7	h-[29px]">
                                    <span class="w-[41.66%] float-left relative min-h-[1px] pr-[15px] pl-0 font-bold text-[13px] text-black leading-7">STONE BREAKDOWN</span>
                                    <span class="w-[33.33%] float-left relative min-h-[1px] p-0 font-bold text-[13px] text-black leading-7" >CATALOG &nbsp;6</span>
                                    <span class="w-[25%] float-left relative min-h-[1px] pr-[15px] pl-[14px] font-bold text-[13px] text-black leading-7">PAGE # &nbsp;12</span>
                                 </h4>
                              </div>
                           </div>
                        </div>
                        <div class=" mx-auto   inline-block pt-[5px] w-full m-0" >
                           <div class="md:w-1/2 float-left  pr-0 pl-[14px]w-full relative min-h-[1px] px-[15px]">
                              <div class="font-ArnoProRegular text-black text-[13px] mb-[10px] " >
                                 <p class="pl-[5px] text-black  border border-solid border-[#efefef] bg-[#efefef] m-0 text-xs font-ProximaNovaRegular ">APPROXIMATE POLISHED DWT <span id="approxpolisheddwtowrding" color="text-red"> </span> 									</p>
                                 <p id="approxpolisheddwt" class="uppercase text-[12px border border-solid border-[#efefef] "> </p>
                                 <input type="hidden" value="4.80" id="org_gold_wt">
                                 <input type="hidden" value="14K WHITE" id="org_metal">
                              </div>
                           </div>
                           <div class="md:w-1/2 float-left  pr-[15px] pl-[14px]w-full relative min-h-[1px] px-[15px]">
                              <div class="font-ArnoProRegular text-black text-[13px] mb-[10px]" >
                                 <p class="pl-[5px] text-black  border border-solid border-[#efefef] bg-[#efefef] m-0 text-xs font-ProximaNovaRegular ">SEMI-MOUNT CTTW</p>
                                 <p id="semimount_carousel" class="uppercase text-[12px] border border-solid border-[#efefef] ">N/A</p>
                              </div>
                           </div>
                        </div>
                        <div class=" mx-auto   inline-block pt-[5px] w-full m-0" >
                           <div class="md:w-1/2 float-left pr-0 pl-[14px]w-full relative min-h-[1px] px-[15px]">
                              <div class="font-ArnoProRegular text-black text-[13px] mb-[10px]">
                                 <p class="pl-[5px] text-black  border border-solid border-[#efefef] bg-[#efefef] m-0 text-xs font-ProximaNovaRegular ">CENTER
                                    SHAPE 
                                 </p>
                                 <p id="center_stone" class=" uppercase text-[12px] border border-solid border-[#efefef] ">ROUND</p>
                              </div>
                           </div>
                           <div class="md:w-1/2 float-left  pr-[15px] pl-[14px]w-full relative min-h-[1px] px-[15px]">
                              <div class="font-ArnoProRegular text-black text-[13px] ">
                                 <p class="pl-[5px] text-black  border border-solid border-[#efefef] bg-[#efefef] m-0 text-xs font-ProximaNovaRegular ">CENTER SIZE </p>
                                 <p class="uppercase border border-solid border-[#efefef] " id="center_size_p_carousel">Fit 1 CT (6.5 MM) <span class="text-red">(not included)</span></p>
                              </div>
                           </div>
                        </div>
                        <div class="clear"></div>
                     </div>
                     <!-- <input type="text" id="delivery_time" name="delivery_time" value="24 hours" readonly="" class="hidden"> -->
                     <div class="lg:w-1/2 float-left  md:w-full  mx-auto   inline-block  relative min-h-[1px] px-[15px]" >
                        <!-- <div class="loadingplease" id="loadingpleasecarousel" class="hidden">
                           <img src="https://www.overnightmountings.com/skin/frontend/default/shopper/images/loading.gif" class="pt-[90px]">
                           </div> -->
                        <div class="font-ArnoProRegular text-black text-[13px] ">
                           <div class="w-auto  mx-auto   inline-block  text-[12px] z-1  m-0 mt-[-10px]">
                              <div class="md:w-full  mx-auto   inline-block float-left  w-full relative min-h-[1px] ">
                                 <div class="font-ArnoProRegular text-black text-[13px] ">
                                    <input type="hidden" id="cur_style1" value="ENG100">
                                    <div class="product-name">
                                       <h3 class="text-[22px] mb-0 uppercase font-medium mt-5 p-0" id="productName"></h3>
                                       <!-- <h3 class="text-[22px] mb-0 uppercase font-medium mt-5 p-0">style # <span class="cur_style">F209S-1.00K4W</span>																					</h3> -->
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <p class="text-[15px] mb-[10px]" id="centersizeDescription"></p>
                           <p id="validationmessage_carousel" class="hidden text-red pl-[64px] m-0">**
                              Select another quality or another level
                           </p>
                           <div class="metal_info"></div>
                           <div>
                           <h4 class="text-[15px] mt-[20px] mb-[10px] flex">ADJUST FIELDS FOR INSTANT PRICING
                              <span data-toggle="modal" data-target="#productDetailModal" class=" ml-[5px] mt-[3px] cursor-pointer max-w-[20px]">
                              <img src="https://www.overnightmountings.com/media/images/tooltip.png" class="max-w-[20px] mt-[-6px] ml-[5px] cursor-pointer">
                              </span>
                           </h4>
                           <div id="cust-op">
                           </div>
                           </div>
                           <div class="no-display">
                           </div>
                           
                           
                         
                           <div class="clear"></div>
                           <div class="clear"></div>
                           <div class="mx-auto   inline-block w-full">
                              <div class="md:w-full  mx-auto   inline-block float-left w-full relative min-h-[1px] ">
                                 <div class="  mx-auto   inline-block w-full">
                                    <div class="w-[41.66%] float-left relative min-h-[1px] pr-[15px]">QUANTITY</div>
                                    <div class="w-[58.33%]  mx-auto   inline-block ">																		
                                       <input type="text" id="qty" name="qty" value="1" disabled="" class=" bg-[#fafafa] w-full h-[24px] text-[13px] border-t-0 border-l-0 border-r-0 border-b-[2px] border-solid border-[#bfbfbf] pl-[2px]">
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <div class="  mx-auto   inline-block w-full">
                              <div class="md:w-full  mx-auto   inline-block float-left  w-full relative min-h-[1px] ">
                                 <div class=" mx-auto   inline-block w-full">
                                    <div class="md:w-1/2 float-left relative min-h-[1px] pr-[15px] pl-[14px]col-xs-6">YOUR PRICE</div>
                                    <div class="md:w-1/2 float-left relative min-h-[1px] pr-[15px] pl-[14px]col-xs-6">
                                       <span class="   text-[22px] float-right" id="showprice_carousel" class="text-[22px] float-right"><span class="price">$<span id="price"></span></span></span>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <div class="  mx-auto   inline-block w-full">
                              <div class="md:w-full  mx-auto   inline-block float-left w-full relative min-h-[1px] ">
                                 <div class="  mx-auto   inline-block w-full">
                                    <div class="md:w-1/2  pl-[14px]w-[41.66%] float-left relative min-h-[1px] pr-[15px]">ASSEMBLE HEAD ?</div>
                                    <div class="md:w-1/2 float-left relative min-h-[1px] pr-[15px] pl-[14px]col-xs-7 top-[-8px]">
                                       <span class="   text-[22px] float-right" id="showprice_carousel" class="text-[22px] float-right"><span class="float-left  left-[-47px] relative text-[13px] font-AronProRegular top-[10px]">YES</span><input id="assemblepopup" name="assemblepopup" type="radio" class="ml-[10px] left-[-52px] relative"><span class="relative font-AronProRegular text-[13px]">NO</span><input id="assemblepopupno" name="assemblepopup" type="radio" class="ml-[10px]  relative left-[-40px]"><span class="price" class=" relative">$20.00</span></span>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <div class="clear"></div>
                           <div class="  mx-auto   inline-block w-full">
                              <div class="md:w-full  mx-auto   inline-block float-left w-full relative min-h-[1px] px-[15px]">
                                 <div class="  mx-auto   inline-block w-full">
                                    <div class="md:w-full  mx-auto   inline-block float-left w-full relative min-h-[1px] px-[15px]" class="text-center">
                                       <button id="addToCart_carousel" type="button" title="Add to Cart" class="w-[95%] border-2 border-solid border-[#cbd5dc] h-[60px] bg-[#E6EBEF] py-2 px-[10px]  hover:bg-black hover:text-white hover:underline hover:border-white" onclick="beforeCarousel();">ADD PEG HEAD</button>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <div class="clear"></div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<script>
    function setval(event) {

        if (event) {
            var selectElement = document.getElementById("subchilds");
            for (i = selectElement.options.length - 1; i >= 0; i--) {
                selectElement.remove(i);
            }
            let categoryId = event;
            const postUrl = "http://local.creationbytamsan.com/ajaxtutorial/result/result/";

            fetch(postUrl, {
                    headers: {
                        contentType: "application/json;charset=utf-8",
                        store: "default",
                    },


                    body: new URLSearchParams({
                        form_key: hyva.getFormKey(),
                        category_id: categoryId,
                        uenc: btoa(window.location.href)
                    }),

                    method: "POST",
                })
                .then(response => response.json())
                .then(data => {
                    getsubcatagories(data);
                });

        }


    }

const getsubcatagories = (catagories) => {

    var mySelect = document.getElementById("subchilds");



    for (var i = 0; i < catagories.length; i++) {
        var opt = catagories[i][1];
        var el = document.createElement("option");
        el.textContent = opt;
        el.value = catagories[i][0];
        mySelect.appendChild(el);


    }


}

function subchildval(event2) {


    if (event2) {
        var ul = document.getElementById("catagoryproducts");
        while (ul.firstChild) {
            ul.removeChild(ul.firstChild);
        }

        let categoryId = event2;
        const postUrl = "http://local.creationbytamsan.com/ajaxtutorial/result2/result2/";

        fetch(postUrl, {
                headers: {
                    contentType: "application/json;charset=utf-8",
                    store: "default",
                },


                body: new URLSearchParams({
                    form_key: hyva.getFormKey(),
                    category_id: categoryId,
                    uenc: btoa(window.location.href)
                }),

                method: "POST",
            })
            .then(response => response.json())
            .then(data => {
                getProducts(data);
            });

    }


}
const getProducts = (catagories) => {

    var ul = document.getElementById("catagoryproducts");
    var modal = document.getElementById("myModal");
    var modalImg = document.getElementById("img01");

    for (var i = 0; i < catagories.length; i++) {
      var src = catagories[i][0];
      var id=catagories[i][1];
      var li = document.createElement("li");
      var img = document.createElement('img');     

      li.classList.add("productsli")
      img.src = src;
      img.alt = id;
      img.classList.add("images");   
      li.appendChild(img);
      ul.appendChild(li);

      img.onclick =function(){
         modal.style.display = "block";
         modalImg.src = this.src;
         
         if (this.alt) {
               let productId = this.alt;
               const postUrl = "http://local.creationbytamsan.com/ajaxtutorial/result2/products/";
       
               fetch(postUrl, {
                       headers: {
                           contentType: "application/json;charset=utf-8",
                           store: "default",
                       },
       
       
                       body: new URLSearchParams({
                           form_key: hyva.getFormKey(),
                           product_id: productId,
                           uenc: btoa(window.location.href)
                       }),
       
                       method: "POST",
                   })
                   .then(response => response.json())
                   .then(data => {
                       getProductDetail(data);
                   });
       
          }       
       
      }       
     


   }
   slider();
    var span = document.getElementsByClassName("close")[0];
    span.onclick = function() {
    modal.style.display = "none";
   }



}

function slider() {


    const next = document.getElementById("btn-next");
    const prev = document.getElementById("btn-prev");
    const matchingsectionpegheadlink = document.getElementById("matchingsectionpegheadlink");


    const numImg = document.querySelectorAll(".images").length;
    const imgcontainer = document.getElementById("catagoryproducts");
    if (numImg == 0) {
        next.style.display = "none";
        prev.style.display = "none";
        matchingsectionpegheadlink.style.display = "none";
    } else {
        next.style.display = "block";
        prev.style.display = "block";
        matchingsectionpegheadlink.style.display = "block";

    }

    let currImg = 1;
    const totalimage = numImg / 2;



    let timeoutID;
    next.addEventListener("click", () => {
        currImg++;


        clearTimeout(timeoutID);
        updateImage();
    });

    prev.addEventListener("click", () => {
        currImg--;


        clearTimeout(timeoutID);

        updateImage();
    });
    updateImage();

    function updateImage() {
        if (currImg > totalimage) {
            currImg = 1;
        } else if (currImg < 1) {
            currImg = totalimage;
        }
        imgcontainer.style.transform = `translateX(-${(currImg - 1) * 360}px)`;


    }

}

const getProductDetail = (Product) => {
   

    var productName = document.getElementById("productName");
    var shortDescription = document.getElementById("centersizeDescription");
    var price = document.getElementById("price");


    //attributes
    var approxpolisheddwt = document.getElementById("approxpolisheddwt");
    var semimount_carousel = document.getElementById("semimount_carousel");

    var center_stone = document.getElementById("center_stone");

    var center_size_p_carousel = document.getElementById("center_size_p_carousel");
    var cust_op = document.getElementById("cust-op");

    while (cust_op.firstChild) {

cust_op.removeChild(cust_op.lastChild);
}


    productName.innerHTML=Product[0][0];
    shortDescription.innerHTML=Product[0][1];
    price.innerHTML=Product[0][2];
    approxpolisheddwt.innerHTML=Product[0][3]; 
    semimount_carousel.innerHTML=Product[0][4];
    center_stone.innerHTML=Product[0][5];
    center_size_p_carousel.innerHTML=Product[0][6];
    var count1=0;
    var totalopt=0;
   
    for (var i = 0; i < Product[0][7].length; i++) {
      var div = document.createElement('div');
       
      var span = document.createElement('span'); 
      span.classList.add("custopTitle");

      var select = document.createElement('select');
      select.classList.add("custopdropdown");

 
      span.innerHTML=  Product[0][7][i];
      div.appendChild(span);
      cust_op.appendChild(div);
     
      count1=count1+totalopt;
     
      totalopt= getOccurrence(Product[0][9], Product[0][7][i]);
   
      for(var j=0; j<totalopt; j++){
        


         var option = document.createElement('option'); 
         option.textContent = Product[0][8][count1+j];

         select.appendChild(option);
         





      }
      
      count=count+totalopt

     div.appendChild(select);

      

  


    }
 
}
function getOccurrence(array, value) {
   count = array.filter(x => x == String(value)).length;
   return count;
}

</script>