<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Customer $customer */
$customer = $viewModels->require(Customer::class);
/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
?>
<div class=" w-full flex flex-wrap pr-4 border-b border-solid border-white pb-11">
    <div class="w-full grid grid-cols-1 sm:grid-cols-4 gap-8 xl:col-span-2">
    <div>
            <h4 class="text-md leading-5 tracking-wider uppercase font-bold text-[24px]">
                Company
            </h4>
            <ul class="">
                <li>
                    <a href="#" class="text-base leading-6">
                        About
                    </a>
                </li>
                <li class="">
                    <a href="http://local.creationbytamsan.com/customer/account/" class="text-base leading-6">
                        My Account                    </a>
                </li>
                                    <li class="">
                        <a href="http://local.creationbytamsan.com/sales/guest/form/" class="text-base leading-6">
                            Orders and Returns                        </a>
                    </li>
                                                    <li class="">
                        <a href="http://local.creationbytamsan.com/search/term/popular/" class="text-base leading-6">
                            Search Terms                        </a>
                    </li>
                                <li class="">
                    <a href="http://local.creationbytamsan.com/contact/" class="text-base leading-6">
                        Contact                    </a>
                </li>
            </ul>
        </div>
        <div>
            <h4 class="text-md leading-5  tracking-wider uppercase font-bold text-[24px]">
                Company
            </h4>
            <ul class="">
                <li>
                    <a href="#" class="text-base leading-6">
                        About
                    </a>
                </li>
                <li class="">
                    <a href="http://local.creationbytamsan.com/customer/account/" class="text-base leading-6">
                        My Account                    </a>
                </li>
                                    <li class="">
                        <a href="http://local.creationbytamsan.com/sales/guest/form/" class="text-base leading-6">
                            Orders and Returns                        </a>
                    </li>
                                                    <li class="">
                        <a href="http://local.creationbytamsan.com/search/term/popular/" class="text-base leading-6">
                            Search Terms                        </a>
                    </li>
                                <li class="">
                    <a href="http://local.creationbytamsan.com/contact/" class="text-base leading-6">
                        Contact                    </a>
                </li>
            </ul>
        </div>
        <div>

            <h4 class="text-md leading-5 tracking-wider uppercase font-bold text-[24px]">
                Company
            </h4>
            <ul class="">
                <li>
                    <a href="#" class="text-base leading-6">
                        About
                    </a>
                </li>
                <li class="">
                    <a href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>"
                       class="text-base leading-6">
                        <?= $escaper->escapeHtml(__('My Account')) ?>
                    </a>
                </li>
                <?php if (!$customer->customerLoggedIn()): ?>
                    <li class="">
                        <a href="<?= $escaper->escapeUrl($block->getUrl('sales/guest/form')) ?>"
                           class="text-base leading-6">
                            <?= $escaper->escapeHtml(__('Orders and Returns')) ?>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($storeConfig->getStoreConfig('catalog/seo/search_terms')): ?>
                    <li class="">
                        <a href="<?= $escaper->escapeUrl($block->getUrl('search/term/popular')) ?>"
                           class="text-base leading-6">
                            <?= $escaper->escapeHtml(__('Search Terms')) ?>
                        </a>
                    </li>
                <?php endif; ?>
                <li class="">
                    <a href="<?= $escaper->escapeUrl($block->getUrl('contact')) ?>"
                       class="text-base leading-6">
                        <?= $escaper->escapeHtml(__('Contact')) ?>
                    </a>
                </li>
            </ul>
        </div>
        <div>
            <h4 class="text-md leading-5  tracking-wider uppercase font-bold text-[24px]">
                Legal
            </h4>
            <ul class="">
                <li class="">
                    <a href="#" class="text-base leading-6">
                        Privacy
                    </a>
                </li>
                <li class="">
                    <a href="#" class="text-base leading-6">
                        Terms and Conditions
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
